### ISSUE TITLE
The demonstration website is not worked

### ISSUE THREAD

**Issue by peter279k** [dmackca/youtube-v3-rss#3]
As title, the [website](http://morning-retreat-1911.herokuapp.com/channelfromusername.php?username=MonsanttoCo) functionality is not available.
Please fix this. Thanks.

**Comment by dmackca** [comment]
I think you've got a typo in the url you tried, "Monsanto" instead of "Monsantto"
It looks like the demo app is working fine, it just doesn't display errors if it doesn't find a given legacy username.

Try this for example: https://morning-retreat-1911.herokuapp.com/channelfromusername.php?username=NardwuarServiette

I can't guarantee that demo will always work, though. I'm happy to answer any questions but I don't plan on updating this old code too much in the future :)
